name: Ivanflores
favicon: null
layout_spectrum: 0.15694
typography_spectrum: 0.84501
title: My project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e7ef'
    - '#302f2d'
    - '#747b83'
    - '#9d9ea0'
    - '#de908c'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
