name: Ivanflores
favicon: null
layout_spectrum: 0.74904
typography_spectrum: 0.84501
title: My project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d3238'
    - '#fefefe'
    - '#4b6a7e'
    - '#fff500'
    - '#fd9b0c'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
