name: Ivanflores
favicon: null
layout_spectrum: 0.45672
typography_spectrum: 0.84501
title: My project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#ebeff2'
    - '#353f41'
    - '#5d737e'
    - '#818d99'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
