name: Ivanflores
favicon: null
layout_spectrum: 0.74904
typography_spectrum: 0.84501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d3238'
    - '#fefefe'
    - '#4b6a7e'
    - '#fff500'
    - '#fd9b0c'
  brandStrength: 0.8361068717204034
  lightness: 0.2783994583878666
  saturation: 0.3743247054517269
  rhythmicContrast: 0.9055513695348054
purpose: []
